[project]
name = "cartes-airports"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "load-dotenv>=0.1.0",
    "matplotlib>=3.7.5",
    "requests-cache>=1.2.1",
]
